name: Deploy SBOMs to DependencyTrack

on:
  pull_request:
    branches: [ "main" ]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read Repository List
        id: read-repos
        run: |
          echo "repos=$(jq -c '.' repos.json)" >> $GITHUB_OUTPUT

      - name: Process Repositories
        env:
          DEPENDENCYTRACK_API_KEY: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
        run: |
          echo '${{ steps.read-repos.outputs.repos }}' | jq -c '.[]' | while read -r repo; do
            repo_name=$(echo "$repo" | jq -r '.name')
            repo_url=$(echo "$repo" | jq -r '.url')
            echo "Processing $repo_name..."
            git clone "$repo_url" || true
            cd "$repo_name" || true
            mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom || true
            echo "Completed $repo_name"
          done

      - name: Deploy SBOM to DependencyTrack
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: 'api.dependencytrack.open-elements.cloud'
          apiKey: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
          projectName: ${{ env.REPO_NAME }}
          projectVersion: 'main'
          bomFilename: "${{ env.REPO_NAME }}/target/bom.xml"
          autoCreate: true
        env:
          REPO_NAME: ${{ env.repo_name }}
