name: Deploy SBOMs to DependencyTrack

on:
  pull_request:
    branches: [ "main" ]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read Repository List
        id: read-repos
        run: |
          echo "repos=$(jq -c '.' repos.json)" >> "$GITHUB_OUTPUT"

      - name: Process Repositories
        env:
          DEPENDENCYTRACK_API_KEY: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
          REPOS_JSON: ${{ steps.read-repos.outputs.repos }}
        run: |
          echo "$REPOS_JSON" | jq -c '.[]' | while read -r repo; do
            repo_name=$(echo "$repo" | jq -r '.name')
            repo_url=$(echo "$repo" | jq -r '.url')
            echo "Cloning $repo_name from $repo_url..."
            git clone "$repo_url" || continue
            cd "$repo_name" || continue

            echo "Generating SBOM for $repo_name..."
            mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom || true

            echo "Uploading SBOM for $repo_name..."
            curl -X POST \
              -H "X-Api-Key: $DEPENDENCYTRACK_API_KEY" \
              -H "Content-Type: application/xml" \
              --data-binary @target/bom.xml \
              "https://api.dependencytrack.open-elements.cloud/api/v1/bom?autoCreate=true&projectName=$repo_name&projectVersion=main" || true

            cd ..
            echo "Completed processing $repo_name"
          done
