name: Deploy SBOMs to DependencyTrack

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read Repository List
        id: read-repos
        run: |
          echo "repos=$(jq -c '.[]' repos.json)" >> $GITHUB_OUTPUT

      - name: Process Repositories
        env:
          DEPENDENCYTRACK_API_KEY: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
        run: |
          for repo in ${{ steps.read-repos.outputs.repos }}; do
            repo_name=$(echo "$repo" | jq -r '.name')
            repo_url=$(echo "$repo" | jq -r '.url')
            echo "Processing $repo_name..."
            git clone "$repo_url" || true
            cd "$repo_name" || true
            mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom || true
            curl -X POST \
              -H "Content-Type: application/xml" \
              -H "X-Api-Key: $DEPENDENCYTRACK_API_KEY" \
              --data-binary "@target/bom.xml" \
              "https://api.dependencytrack.open-elements.cloud/api/v1/bom?projectName=$repo_name&projectVersion=main&autoCreate=true" || true
            cd ..
            echo "Completed $repo_name"
          done
